baseURL = 'https://raim.dev/'
languageCode = 'en-us'
title = 'TIL of Raimbek'
enableRobotsTXT = true

theme = "til"

[permalinks]
  posts = '/posts/:title/'

[caches]
  [caches.images]
    dir = ':cacheDir/images'